# -*- mode: ruby -*-
# vi: set ft=ruby :
    
#hostnamectl set-hostname cydata

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1504"
  config.vm.hostname = "cydata"
  config.vm.network "public_network"
  config.vm.synced_folder "../sql", "/cypress/data/sql"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y vim tmux postgresql postgresql-contrib postgresql-doc
  SHELL
end
